// templates/angular/src/app/features/skills/skills.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { portfolioConfig } from '../../portfolio.config';

@Component({
  selector: 'app-skills',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './skills.component.html'
})
export class SkillsComponent {
  skills = {
    title: 'Skills',
    categories: portfolioConfig.skills,
  };
}

<div class="shared-style fade-in">
  <h2>{{ skills.title }}</h2>
  <div class="skills-grid">
    @for (category of skills.categories; track $index) {
      <div class="skill-category">
        <div class="category-header">
          <div class="category-icon">
            <i class="bi" [ngClass]="{
              'bi-code-square': category.name.includes('.NET'),
              'bi-database': category.name.includes('Database'),
              'bi-palette': category.name.includes('Client'),
              'bi-git': category.name.includes('Version')
            }"></i>
          </div>
          <h3>{{ category.name }}</h3>
        </div>
        <div class="skill-tags">
          @for (skill of category.skills; track $index) {
            <span class="skill-tag">{{ skill }}</span>
          }
        </div>
      </div>
    }
  </div>
</div>

<style>

.skills-grid {
    display: grid;
    grid-template-columns: repeat(2, 1fr);
    gap: 20px;
    margin-top: 20px;
}

.skill-category {
    padding: 24px;
    border-radius: 10px;
    background: #f8fafc;
    border: 1px solid #e2e8f0;
    transition: all 0.2s ease;
    min-height: 180px;
    display: flex;
    flex-direction: column;
}

.skill-category:hover {
    border-color: #cbd5e1;
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.06);
}

.category-header {
    display: flex;
    align-items: center;
    margin-bottom: 16px;
    gap: 12px;
}

.category-icon {
    width: 40px;
    height: 40px;
    border-radius: 8px;
    background: #2563eb;
    display: flex;
    align-items: center;
    justify-content: center;
    color: white;
    font-size: 1.25rem;
    flex-shrink: 0;
}

h3 {
    color: #0f172a;
    font-family: 'Inter', sans-serif;
    font-size: 1.0625rem;
    font-weight: 700;
    margin: 0;
    letter-spacing: -0.01em;
}

.skill-tags {
    display: flex;
    flex-wrap: wrap;
    gap: 8px;
}

.skill-tag {
    background: #2563eb;
    color: white;
    padding: 6px 14px;
    border-radius: 20px;
    font-size: 0.8125rem;
    font-weight: 600;
    transition: all 0.2s ease;
    cursor: default;
}

.skill-tag:hover {
    background: #1d4ed8;
    transform: translateY(-1px);
}

@media (max-width: 768px) {
    .skills-grid {
        grid-template-columns: 1fr;
        gap: 14px;
    }

    .skill-category {
        padding: 20px;
    }

    h3 {
        font-size: 1rem;
    }

    .skill-tag {
        font-size: 0.75rem;
        padding: 5px 12px;
    }

    .category-icon {
        width: 36px;
        height: 36px;
        font-size: 1.125rem;
    }
}

@media (max-width: 480px) {
    .skill-category {
        padding: 16px;
    }

    h3 {
        font-size: 0.9375rem;
    }

    .skill-tag {
        font-size: 0.6875rem;
        padding: 4px 10px;
    }
}

</style>

// templates/nextjs/src/components/sections/Skills.tsx
import portfolioConfig from '@/config/portfolio.config';
import { BiCodeSquare, BiData, BiPalette, BiGitBranch } from 'react-icons/bi';
import type { IconType } from 'react-icons';

const CATEGORY_ICON_MAP: Array<{ keyword: string; Icon: IconType }> = [
  { keyword: '.NET', Icon: BiCodeSquare },
  { keyword: 'Database', Icon: BiData },
  { keyword: 'Client', Icon: BiPalette },
  { keyword: 'Version', Icon: BiGitBranch },
];

function getCategoryIcon(name: string): IconType {
  return CATEGORY_ICON_MAP.find((m) => name.includes(m.keyword))?.Icon ?? BiCodeSquare;
}

export default function Skills() {
  const { skills } = portfolioConfig;

  return (
    <div className="section-card fade-in">
      <h2 className="section-title">Skills</h2>
      <div className="grid grid-cols-1 sm:grid-cols-2 gap-5 mt-5">
        {skills.map((category) => {
          const Icon = getCategoryIcon(category.name);
          return (
            <div
              key={category.name}
              className="p-6 rounded-[10px] bg-slate-50 border border-slate-200 transition-all duration-200 hover:border-slate-300 hover:shadow-md min-h-[180px] flex flex-col"
            >
              <div className="flex items-center gap-3 mb-4">
                <div className="w-10 h-10 rounded-lg bg-blue-600 flex items-center justify-center text-white text-xl flex-shrink-0">
                  <Icon />
                </div>
                <h3 className="text-[1.0625rem] font-bold text-slate-900 font-sans tracking-tight m-0">
                  {category.name}
                </h3>
              </div>
              <div className="flex flex-wrap gap-2">
                {category.skills.map((skill) => (
                  <span key={skill} className="skill-badge">
                    {skill}
                  </span>
                ))}
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}
