// templates/nextjs/src/components/sections/ContentCreator.tsx
import portfolioConfig from '@/config/portfolio.config';
import { BiPencilSquare, BiLogoMediumSquare, BiLogoYoutube } from 'react-icons/bi';
import type { IconType } from 'react-icons';
import type { ContentPlatform } from '@/config/portfolio.types';

const PLATFORM_ICONS: Record<string, IconType> = {
  blog: BiPencilSquare,
  medium: BiLogoMediumSquare,
  youtube: BiLogoYoutube,
  custom: BiPencilSquare,
};

function PlatformCard({ platform }: { platform: ContentPlatform }) {
  const Icon = PLATFORM_ICONS[platform.icon] ?? BiPencilSquare;

  return (
    <a
      href={platform.url}
      target="_blank"
      rel="noopener noreferrer"
      className="block rounded-xl overflow-hidden border border-slate-200 no-underline transition-all duration-200 hover:-translate-y-1 hover:shadow-lg"
    >
      {/* Gradient header */}
      <div
        className="flex items-center gap-3 px-5 py-4 text-white"
        style={{ background: platform.gradient }}
      >
        <Icon className="text-2xl flex-shrink-0" />
        <span className="font-bold text-base">{platform.name}</span>
      </div>
      {/* Description */}
      <div className="px-5 py-4 bg-white">
        <p className="text-slate-500 text-sm leading-relaxed m-0">{platform.description}</p>
      </div>
    </a>
  );
}

export default function ContentCreator() {
  const { contentCreation } = portfolioConfig;

  return (
    <div className="section-card fade-in">
      <h2 className="section-title">Content Creation &amp; Blogging</h2>
      <p className="text-slate-500 text-base mb-6">{contentCreation.description}</p>

      {/* Platform cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 mb-8">
        {contentCreation.platforms.map((platform) => (
          <PlatformCard key={platform.name} platform={platform} />
        ))}
      </div>

      {/* Topics */}
      <div>
        <p className="text-xs font-semibold uppercase tracking-widest text-slate-400 mb-3">Topics I write about</p>
        <div className="flex flex-wrap gap-2">
          {contentCreation.topics.map((topic) => (
            <span
              key={topic}
              className="inline-block px-4 py-1.5 rounded-full border border-blue-200 text-blue-600 text-sm font-semibold bg-blue-50 transition-all duration-200 hover:bg-blue-600 hover:text-white hover:border-blue-600"
            >
              {topic}
            </span>
          ))}
        </div>
      </div>
    </div>
  );
}

// templates/angular/src/app/features/content-creator/content-creator.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { portfolioConfig } from '../../portfolio.config';

@Component({
  selector: 'app-content-creator',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './content-creator.component.html'
})
export class ContentCreatorComponent {
  contentData = {
    title: 'Content Creation & Blogging',
    description: portfolioConfig.contentCreation.description,
    platforms: portfolioConfig.contentCreation.platforms,
    topics: portfolioConfig.contentCreation.topics,
  };
}

<div class="shared-style fade-in">
  <h2>{{ contentData.title }}</h2>
  
  <div class="content-intro">
    <div class="intro-icon">
      <i class="bi bi-pen-fill"></i>
    </div>
    <p class="intro-text">{{ contentData.description }}</p>
  </div>

  <div class="platforms-grid">
    @for (platform of contentData.platforms; track $index) {
      <a [href]="platform.url" target="_blank" rel="noopener noreferrer" class="platform-card">
        <div class="platform-icon" [style.background]="platform.gradient">
          <i class="bi" [ngClass]="platform.icon"></i>
        </div>
        <div class="platform-content">
          <h3>{{ platform.name }}</h3>
          <p>{{ platform.description }}</p>
        </div>
        <div class="platform-arrow">
          <i class="bi bi-arrow-right"></i>
        </div>
      </a>
    }
  </div>

  <div class="topics-section">
    <div class="topics-header">
      <i class="bi bi-bookmark-star-fill"></i>
      <span>Topics I Write About</span>
    </div>
    <div class="topics-tags">
      @for (topic of contentData.topics; track $index) {
        <span class="topic-tag">{{ topic }}</span>
      }
    </div>
  </div>
</div>

<style>
.content-intro {
    display: flex;
    align-items: flex-start;
    gap: 14px;
    padding: 20px 20px 20px 24px;
    background: #f8fafc;
    border-radius: 10px;
    margin-bottom: 28px;
    border-left: 3px solid #2563eb;
}

.intro-icon {
    width: 40px;
    height: 40px;
    min-width: 40px;
    border-radius: 8px;
    background: #2563eb;
    display: flex;
    align-items: center;
    justify-content: center;
    color: white;
    font-size: 1.25rem;
}

.intro-text {
    line-height: 1.7;
    color: #475569;
    margin: 0;
    font-size: 0.9375rem;
    font-weight: 400;
}

.platforms-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(260px, 1fr));
    gap: 14px;
    margin-bottom: 28px;
}

.platform-card {
    display: flex;
    align-items: center;
    gap: 14px;
    padding: 18px;
    background: #f8fafc;
    border-radius: 10px;
    border: 1px solid #e2e8f0;
    text-decoration: none;
    transition: all 0.2s ease;
}

.platform-card:hover {
    border-color: #cbd5e1;
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.06);
    transform: translateY(-2px);
}

.platform-icon {
    width: 48px;
    height: 48px;
    min-width: 48px;
    border-radius: 10px;
    display: flex;
    align-items: center;
    justify-content: center;
    color: white;
    font-size: 1.5rem;
}

.platform-content {
    flex: 1;
}

.platform-content h3 {
    color: #0f172a;
    font-family: 'Inter', sans-serif;
    font-size: 1rem;
    font-weight: 700;
    margin: 0 0 4px 0;
}

.platform-content p {
    color: #64748b;
    font-size: 0.8125rem;
    margin: 0;
    line-height: 1.4;
}

.platform-arrow {
    color: #2563eb;
    font-size: 1.125rem;
    transition: transform 0.2s ease;
}

.platform-card:hover .platform-arrow {
    transform: translateX(4px);
}

.topics-section {
    padding: 20px;
    background: #f8fafc;
    border-radius: 10px;
    border: 1px solid #e2e8f0;
}

.topics-header {
    display: flex;
    align-items: center;
    gap: 8px;
    margin-bottom: 14px;
    font-weight: 700;
    color: #0f172a;
    font-size: 1rem;
}

.topics-header i {
    color: #d97706;
    font-size: 1.125rem;
}

.topics-tags {
    display: flex;
    flex-wrap: wrap;
    gap: 8px;
}

.topic-tag {
    display: inline-block;
    padding: 8px 16px;
    background: #fffbeb;
    border: 1px solid #fde68a;
    border-radius: 8px;
    color: #d97706;
    font-size: 0.8125rem;
    font-weight: 600;
    transition: all 0.2s ease;
}

.topic-tag:hover {
    background: #d97706;
    color: white;
    border-color: #d97706;
}

@media (max-width: 768px) {
    .platforms-grid {
        grid-template-columns: 1fr;
        gap: 12px;
    }

    .platform-card {
        padding: 14px;
    }

    .platform-icon {
        width: 40px;
        height: 40px;
        min-width: 40px;
        font-size: 1.25rem;
    }

    .platform-content h3 {
        font-size: 0.9375rem;
    }
}

@media (max-width: 600px) {
    .content-intro {
        flex-direction: column;
        text-align: center;
        align-items: center;
        padding: 16px;
    }

    .intro-text {
        font-size: 0.875rem;
    }

    .platform-card {
        flex-direction: column;
        text-align: center;
    }

    .platform-arrow {
        display: none;
    }

    .topics-section {
        padding: 16px;
    }

    .topic-tag {
        font-size: 0.75rem;
        padding: 6px 12px;
    }
}
</style>
