// templates/angular/src/app/features/education/education.component.ts
import { Component } from '@angular/core';
import { portfolioConfig } from '../../portfolio.config';

@Component({
  selector: 'app-education',
  standalone: true,
  imports: [],
  templateUrl: './education.component.html'
})
export class EducationComponent {
  educationDetails = portfolioConfig.education;
}

<div class="shared-style fade-in">
  <h2>Education</h2>

  <div class="education-list">
    @for (education of educationDetails; track $index) {
      <div class="education-card">
        <div class="education-header">
          <div class="degree-icon">
            <i class="bi bi-mortarboard-fill"></i>
          </div>
          <div class="degree-info">
            <h3>{{ education.degree }}</h3>
            <p class="institution">
              <i class="bi bi-building"></i>
              {{ education.institution }}
            </p>
          </div>
        </div>
        
        <div class="education-details">
          <div class="detail-item">
            <i class="bi bi-calendar-range"></i>
            <span>{{ education.startDate }} - {{ education.endDate }}</span>
          </div>
          <div class="detail-item grade">
            <i class="bi bi-award-fill"></i>
            <span>Grade: <strong>{{ education.grade }}</strong></span>
          </div>
        </div>
        
        <div class="courses-section">
          <div class="courses-header">
            <i class="bi bi-book-fill"></i>
            <span>Relevant Courses</span>
          </div>
          <div class="courses-grid">
            @for (course of education.courses; track $index) {
              <span class="course-tag">{{ course }}</span>
            }
          </div>
        </div>
      </div>
    }
  </div>
</div>

<style>

.education-list {
    display: flex;
    flex-direction: column;
    gap: 20px;
}

.education-card {
    background: #f8fafc;
    border-radius: 10px;
    padding: 24px;
    border: 1px solid #e2e8f0;
    transition: all 0.2s ease;
}

.education-card:hover {
    border-color: #cbd5e1;
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.06);
}

.education-header {
    display: flex;
    align-items: flex-start;
    gap: 16px;
    margin-bottom: 20px;
    padding-bottom: 16px;
    border-bottom: 1px solid #e2e8f0;
}

.degree-icon {
    width: 48px;
    height: 48px;
    border-radius: 10px;
    background: #2563eb;
    display: flex;
    align-items: center;
    justify-content: center;
    color: white;
    font-size: 1.5rem;
    flex-shrink: 0;
}

.degree-info {
    flex: 1;
}

h3 {
    color: #0f172a;
    font-family: 'Inter', sans-serif;
    font-size: 1.25rem;
    font-weight: 700;
    margin: 0 0 6px 0;
}

.institution {
    display: flex;
    align-items: center;
    gap: 6px;
    color: #64748b;
    font-size: 0.9375rem;
    font-weight: 500;
    margin: 0;
}

.institution i {
    color: #2563eb;
}

.education-details {
    display: flex;
    flex-wrap: wrap;
    gap: 12px;
    margin-bottom: 20px;
}

.detail-item {
    display: flex;
    align-items: center;
    gap: 6px;
    padding: 8px 14px;
    background: #eff6ff;
    border-radius: 8px;
    color: #475569;
    font-size: 0.875rem;
    font-weight: 600;
}

.detail-item i {
    color: #2563eb;
    font-size: 1rem;
}

.detail-item.grade {
    background: #ecfdf5;
}

.detail-item.grade i {
    color: #059669;
}

.detail-item.grade strong {
    color: #059669;
}

.courses-section {
    margin-top: 20px;
}

.courses-header {
    display: flex;
    align-items: center;
    gap: 8px;
    margin-bottom: 12px;
    font-weight: 700;
    color: #0f172a;
    font-size: 0.9375rem;
}

.courses-header i {
    color: #2563eb;
}

.courses-grid {
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(180px, 1fr));
    gap: 8px;
}

.course-tag {
    display: flex;
    align-items: center;
    padding: 8px 12px;
    background: #f1f5f9;
    border: 1px solid #e2e8f0;
    border-radius: 8px;
    color: #475569;
    font-size: 0.8125rem;
    font-weight: 600;
    transition: all 0.2s ease;
    text-align: center;
    justify-content: center;
}

.course-tag:hover {
    background: #2563eb;
    color: white;
    border-color: #2563eb;
}

@media (max-width: 768px) {
    .education-card {
        padding: 20px;
    }
    
    .degree-icon {
        width: 40px;
        height: 40px;
        font-size: 1.25rem;
    }

    h3 {
        font-size: 1.125rem;
    }

    .courses-grid {
        grid-template-columns: repeat(auto-fill, minmax(150px, 1fr));
        gap: 6px;
    }
}

@media (max-width: 600px) {
    .education-card {
        padding: 16px;
    }
    
    .education-header {
        flex-direction: column;
        text-align: center;
        align-items: center;
    }

    h3 {
        font-size: 1rem;
    }

    .institution {
        justify-content: center;
        font-size: 0.875rem;
    }

    .education-details {
        flex-direction: column;
        gap: 8px;
    }
    
    .detail-item {
        justify-content: center;
    }

    .courses-grid {
        grid-template-columns: 1fr;
    }
    
    .course-tag {
        font-size: 0.75rem;
    }
}

</style>

// templates/react/src/components/sections/Education.tsx
import portfolioConfig from '@/config/portfolio.config';
import { BiBook, BiCalendar, BiMedal } from 'react-icons/bi';

export default function Education() {
  const { education } = portfolioConfig;

  return (
    <div className="section-card fade-in">
      <h2 className="section-title">Education</h2>
      <div className="space-y-6">
        {education.map((edu, i) => (
          <div
            key={i}
            className="p-6 bg-slate-50 rounded-[10px] border border-slate-200 transition-all duration-200 hover:border-slate-300 hover:shadow-md"
          >
            {/* Header */}
            <div className="flex items-start gap-4 mb-4">
              <div className="w-12 h-12 rounded-xl bg-blue-600 flex items-center justify-center text-white text-2xl flex-shrink-0">
                <BiBook />
              </div>
              <div className="flex-1 min-w-0">
                <h3 className="font-sans text-xl font-bold text-slate-900 mb-1 tracking-tight">
                  {edu.degree}
                </h3>
                <p className="text-blue-600 font-semibold text-base">{edu.institution}</p>
              </div>
            </div>

            {/* Meta: dates + grade */}
            <div className="flex flex-wrap gap-3 mb-5">
              <span className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-white rounded-lg border border-slate-200 text-sm font-medium text-slate-600">
                <BiCalendar className="text-slate-400" />
                {edu.startDate} – {edu.endDate}
              </span>
              <span className="inline-flex items-center gap-1.5 px-3 py-1.5 bg-emerald-50 rounded-lg border border-emerald-100 text-sm font-semibold text-emerald-600">
                <BiMedal />
                Grade: {edu.grade}
              </span>
            </div>

            {/* Coursework */}
            {edu.courses.length > 0 && (
              <div>
                <p className="text-xs font-semibold uppercase tracking-widest text-slate-400 mb-2">
                  Relevant Coursework
                </p>
                <div className="flex flex-wrap gap-2">
                  {edu.courses.map((course) => (
                    <span
                      key={course}
                      className="inline-block px-3 py-1 bg-white border border-slate-200 rounded-full text-xs font-medium text-slate-600 transition-all duration-200 hover:border-blue-300 hover:text-blue-600"
                    >
                      {course}
                    </span>
                  ))}
                </div>
              </div>
            )}
          </div>
        ))}
      </div>
    </div>
  );
}
