// templates/angular/src/app/features/employment/employment.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { portfolioConfig, ExperienceEntry } from '../../portfolio.config';

@Component({
  selector: 'app-employment',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './employment.component.html'
})
export class EmploymentComponent implements OnInit {
  employmentData: Employment | undefined;

  jobs: ExperienceEntry[] = portfolioConfig.experience.jobs;
  trainingExperiences: ExperienceEntry[] = portfolioConfig.experience.training;

  ngOnInit(): void {
    this.employmentData = {
      entries: this.jobs,
      trainingEntries: this.trainingExperiences,
      totalExperience: this.calculateTotalExperience(this.jobs),
    };
  }

  calculateTotalExperience(entries: ExperienceEntry[]): number {
    let totalExperience = 0;
    const currentDate = new Date();

    for (const entry of entries) {
      const startDate = new Date(this.parseDate(entry.startDate));
      const endDate = entry.endDate === 'Present' ? currentDate : new Date(this.parseDate(entry.endDate));
      
      const yearDiff = endDate.getFullYear() - startDate.getFullYear();
      const monthDiff = endDate.getMonth() - startDate.getMonth();
      
      totalExperience += yearDiff + (monthDiff / 12);
    }

    return Math.ceil(totalExperience * 10) / 10; 
  }

  parseDate(dateString: string): string {
    const [month, year] = dateString.split(' ');
    const monthIndex = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'].indexOf(month);
    return `${year}-${(monthIndex + 1).toString().padStart(2, '0')}-01`;
  }

  calculateDuration(startDate: string, endDate: string): string {
    const start = new Date(this.parseDate(startDate));
    const end = endDate === 'Present' ? new Date() : new Date(this.parseDate(endDate));
    
    let years = end.getFullYear() - start.getFullYear();
    let months = end.getMonth() - start.getMonth();
    
    // Adjust for day of month differences
    if (end.getDate() < start.getDate()) {
      months--;
    }
    
    if (months < 0) {
      years--;
      months += 12;
    }
    
    const parts: string[] = [];
    if (years > 0) {
      parts.push(`${years} year${years > 1 ? 's' : ''}`);
    }
    if (months > 0) {
      parts.push(`${months} month${months > 1 ? 's' : ''}`);
    }
    
    return parts.length > 0 ? parts.join(' ') : 'Less than 1 month';
  }

}

interface Employment {
  totalExperience: number;
  entries: ExperienceEntry[];
  trainingEntries?: ExperienceEntry[];
}

<div class="shared-style fade-in">
  <h2>Employment History</h2>
  <div class="experience-badge">
    <i class="bi bi-briefcase-fill"></i>
    <span>{{ employmentData?.totalExperience }}+ years of experience</span>
  </div>
  
  <div class="employment-timeline">
    @for (entry of employmentData?.entries; track $index) {
      <div class="timeline-item">
        <div class="timeline-dot"></div>
        <div class="timeline-content">
          <div class="employment-header">
            <div class="header-main">
              <h3>{{ entry.position }}</h3>
              <div class="job-meta">
                <span class="job-type {{ entry.jobType === 'Remote' ? 'remote' : 'onsite' }}">
                  <i class="bi" [ngClass]="entry.jobType === 'Remote' ? 'bi-house-fill' : 'bi-building'"></i>
                  {{ entry.jobType }}
                </span>
                <span class="job-location">
                  <i class="bi bi-geo-alt-fill"></i>
                  {{ entry.location }}
                </span>
              </div>
            </div>
            <div class="company-info">
              <a [href]="entry.companyUrl" target="_blank" rel="noopener noreferrer" class="company-link">
                <i class="bi bi-building"></i>
                {{ entry.company }}
              </a>
              <span class="date-range">
                <i class="bi bi-calendar3"></i>
                {{ entry.startDate }} - {{ entry.endDate }}
                <span class="duration">({{ calculateDuration(entry.startDate, entry.endDate) }})</span>
              </span>
            </div>
          </div>
          
          <p class="description">{{ entry.description }}</p>
          
          <div class="skills-wrapper">
            <div class="skills-label">
              <i class="bi bi-gear-fill"></i>
              Technologies:
            </div>
            <div class="skills-tags">
              @for (skill of entry.skills; track $index) {
                <span class="skill-badge">{{ skill }}</span>
              }
            </div>
          </div>
        </div>
      </div>
    }
  </div>
  
  <!-- Part-Time Training Experience -->
  @if (employmentData?.trainingEntries && (employmentData?.trainingEntries?.length ?? 0) > 0) {
    <div class="section-divider"></div>
    <h2 class="training-title">
      <i class="bi bi-award-fill"></i>
      Part-Time Training Experience
    </h2>
    <div class="employment-timeline">
      @for (entry of employmentData?.trainingEntries; track $index) {
        <div class="timeline-item training-item">
          <div class="timeline-dot training-dot"></div>
          <div class="timeline-content">
            <div class="employment-header">
              <div class="header-main">
                <h3>{{ entry.position }}</h3>
                <div class="job-meta">
                  <span class="job-type part-time">
                    <i class="bi bi-clock-history"></i>
                    Part-Time
                  </span>
                  <span class="job-location">
                    <i class="bi bi-geo-alt-fill"></i>
                    {{ entry.location }}
                  </span>
                </div>
              </div>
              <div class="company-info">
                <a [href]="entry.companyUrl" target="_blank" rel="noopener noreferrer" class="company-link">
                  <i class="bi bi-building"></i>
                  {{ entry.company }}
                </a>
                <span class="date-range">
                  <i class="bi bi-calendar3"></i>
                  {{ entry.startDate }} - {{ entry.endDate }}
                  <span class="duration">({{ calculateDuration(entry.startDate, entry.endDate) }})</span>
                </span>
              </div>
            </div>
            
            <p class="description">{{ entry.description }}</p>
            
            <div class="skills-wrapper">
              <div class="skills-label">
                <i class="bi bi-gear-fill"></i>
                Technologies:
              </div>
              <div class="skills-tags">
                @for (skill of entry.skills; track $index) {
                  <span class="skill-badge">{{ skill }}</span>
                }
              </div>
            </div>
          </div>
        </div>
      }
    </div>
  }
</div>

<style>

.experience-badge {
    display: inline-flex;
    align-items: center;
    gap: 8px;
    padding: 10px 18px;
    background: #2563eb;
    color: white;
    border-radius: 20px;
    font-weight: 600;
    font-size: 0.875rem;
    margin-bottom: 28px;
}

.experience-badge i {
    font-size: 1.125rem;
}

.employment-timeline {
    position: relative;
    padding-left: 32px;
}

.employment-timeline::before {
    content: '';
    position: absolute;
    left: 0;
    top: 16px;
    bottom: 16px;
    width: 2px;
    background: #2563eb;
    border-radius: 2px;
}

.timeline-item {
    position: relative;
    margin-bottom: 32px;
    padding-left: 24px;
}

.timeline-item:last-child {
    margin-bottom: 0;
}

.timeline-dot {
    position: absolute;
    left: -37px;
    top: 8px;
    width: 14px;
    height: 14px;
    border-radius: 50%;
    background: white;
    border: 3px solid #2563eb;
    transition: all 0.2s ease;
    z-index: 1;
}

.timeline-item:hover .timeline-dot {
    box-shadow: 0 0 0 4px rgba(37, 99, 235, 0.15);
}

.timeline-content {
    background: #f8fafc;
    border-radius: 10px;
    padding: 24px;
    border: 1px solid #e2e8f0;
    transition: all 0.2s ease;
}

.timeline-item:hover .timeline-content {
    border-color: #cbd5e1;
    box-shadow: 0 4px 12px rgba(0, 0, 0, 0.06);
}

.employment-header {
    margin-bottom: 16px;
}

.header-main {
    margin-bottom: 12px;
}

h3 {
    color: #0f172a;
    font-family: 'Inter', sans-serif;
    font-size: 1.25rem;
    font-weight: 700;
    margin: 0 0 8px 0;
    letter-spacing: -0.01em;
}

.job-meta {
    display: flex;
    flex-wrap: wrap;
    gap: 8px;
    margin-top: 8px;
}

.job-type, .job-location {
    display: inline-flex;
    align-items: center;
    gap: 5px;
    padding: 4px 10px;
    border-radius: 6px;
    font-size: 0.8125rem;
    font-weight: 600;
}

.job-type {
    background: #eff6ff;
    color: #2563eb;
}

.job-type.remote {
    background: #ecfdf5;
    color: #059669;
}

.job-location {
    background: #fffbeb;
    color: #d97706;
}

.company-info {
    display: flex;
    flex-wrap: wrap;
    align-items: center;
    gap: 16px;
    padding: 10px 0;
    border-top: 1px solid #e2e8f0;
}

.company-link {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    color: #2563eb;
    text-decoration: none;
    font-weight: 600;
    font-size: 0.9375rem;
    transition: color 0.2s ease;
}

.company-link:hover {
    color: #1d4ed8;
}

.date-range {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    color: #64748b;
    font-weight: 500;
    font-size: 0.875rem;
}

.date-range .duration {
    color: #2563eb;
    font-weight: 600;
    margin-left: 4px;
}

.description {
    line-height: 1.7;
    color: #475569;
    margin-bottom: 16px;
    font-size: 0.9375rem;
}

.skills-wrapper {
    margin-top: 16px;
}

.skills-label {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    font-weight: 600;
    color: #1e293b;
    margin-bottom: 10px;
    font-size: 0.8125rem;
    text-transform: uppercase;
    letter-spacing: 0.03em;
}

.skills-tags {
    display: flex;
    flex-wrap: wrap;
    gap: 6px;
}

.skill-badge {
    display: inline-block;
    padding: 5px 12px;
    background: #2563eb;
    color: white;
    border-radius: 14px;
    font-size: 0.75rem;
    font-weight: 600;
    transition: background 0.2s ease;
}

.skill-badge:hover {
    background: #1d4ed8;
}

.section-divider {
    height: 1px;
    background: #e2e8f0;
    margin: 36px 0 28px 0;
}

.training-title {
    display: flex;
    align-items: center;
    gap: 10px;
    color: #0f172a;
    font-size: 1.5rem;
    font-weight: 800;
    margin-bottom: 24px;
    letter-spacing: -0.02em;
}

.training-title i {
    color: #0ea5e9;
}

.training-item .timeline-dot {
    background: white;
    border-color: #0ea5e9;
}

.training-item:hover .timeline-dot {
    box-shadow: 0 0 0 4px rgba(14, 165, 233, 0.15);
}

.job-type.part-time {
    background: #f0f9ff;
    color: #0ea5e9;
}

@media (max-width: 768px) {
    .employment-timeline {
        padding-left: 20px;
    }
    
    .timeline-item {
        padding-left: 16px;
    }
    
    .timeline-dot {
        left: -29px;
        width: 12px;
        height: 12px;
    }

    h3 {
        font-size: 1.125rem;
    }

    .company-link {
        font-size: 0.875rem;
    }

    .description {
        font-size: 0.875rem;
    }

    .skill-badge {
        font-size: 0.6875rem;
        padding: 4px 10px;
    }
}

@media (max-width: 600px) {
    .employment-timeline {
        padding-left: 16px;
    }
    
    .timeline-item {
        padding-left: 14px;
        margin-bottom: 24px;
    }
    
    .timeline-dot {
        left: -25px;
        width: 10px;
        height: 10px;
    }
    
    .timeline-content {
        padding: 16px;
    }

    h3 {
        font-size: 1rem;
    }

    .job-meta {
        flex-direction: column;
        gap: 6px;
    }

    .company-info {
        flex-direction: column;
        align-items: flex-start;
        gap: 6px;
    }

    .description {
        font-size: 0.8125rem;
    }

    .skill-badge {
        font-size: 0.625rem;
        padding: 3px 8px;
    }
}

</style>

// templates/react/src/components/sections/Employment.tsx
import portfolioConfig from '@/config/portfolio.config';
import type { ExperienceEntry } from '@/config/portfolio.types';
import {
  BiBriefcase as BiBriefcaseFilled,
  BiBuilding,
  BiHome,
  BiMapPin,
  BiCalendar,
  BiCog,
  BiAward,
  BiHistory,
} from 'react-icons/bi';

function parseDate(dateStr: string): Date {
  if (dateStr === 'Present') return new Date();
  const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
  const [m, y] = dateStr.split(' ');
  return new Date(parseInt(y, 10), months.indexOf(m), 1);
}

function calculateDuration(start: string, end: string): string {
  const s = parseDate(start);
  const e = parseDate(end);
  let years = e.getFullYear() - s.getFullYear();
  let months = e.getMonth() - s.getMonth();
  if (months < 0) {
    years--;
    months += 12;
  }
  const parts: string[] = [];
  if (years > 0) parts.push(`${years} yr${years > 1 ? 's' : ''}`);
  if (months > 0) parts.push(`${months} mo`);
  return parts.length ? parts.join(' ') : '< 1 mo';
}

function calculateTotalYears(entries: ExperienceEntry[]): number {
  let total = 0;
  for (const e of entries) {
    const s = parseDate(e.startDate);
    const end = parseDate(e.endDate);
    total += (end.getTime() - s.getTime()) / (1000 * 60 * 60 * 24 * 365.25);
  }
  return Math.ceil(total * 10) / 10;
}

function TimelineEntry({ entry, isTraining }: { entry: ExperienceEntry; isTraining?: boolean }) {
  const accentColor = isTraining ? '#0891b2' : '#1f6feb';

  return (
    <div className="relative mb-8 pl-6 last:mb-0">
      <div
        className="absolute left-[-33px] top-4 z-10 h-3.5 w-3.5 rounded-full border-[3px] bg-white"
        style={{ borderColor: accentColor }}
      />

      <div className="surface-card surface-card-hover p-6">
        <div className="mb-4">
          <h3 className="mb-3 text-xl font-extrabold tracking-normal text-slate-950">{entry.position}</h3>
          <div className="flex flex-wrap gap-2">
            <span
              className={`inline-flex items-center gap-1.5 rounded-md px-2.5 py-1 text-[0.8125rem] font-bold ${
                isTraining
                  ? 'bg-cyan-50 text-cyan-700'
                  : entry.jobType === 'Remote'
                    ? 'bg-emerald-50 text-emerald-700'
                    : 'bg-blue-50 text-blue-700'
              }`}
            >
              {isTraining ? (
                <>
                  <BiHistory className="text-sm" /> Part-Time
                </>
              ) : entry.jobType === 'Remote' ? (
                <>
                  <BiHome className="text-sm" /> Remote
                </>
              ) : (
                <>
                  <BiBuilding className="text-sm" /> On-site
                </>
              )}
            </span>
            <span className="inline-flex items-center gap-1.5 rounded-md bg-amber-50 px-2.5 py-1 text-[0.8125rem] font-bold text-amber-700">
              <BiMapPin className="text-sm" />
              {entry.location}
            </span>
          </div>
        </div>

        <div className="mb-4 flex flex-wrap items-center gap-4 border-b border-slate-200 pb-3">
          <a
            href={entry.companyUrl}
            target="_blank"
            rel="noopener noreferrer"
            className="inline-flex items-center gap-1.5 text-[0.9375rem] font-extrabold text-blue-700 no-underline transition hover:text-cyan-700"
          >
            <BiBuilding className="text-base" />
            {entry.company}
          </a>
          <span className="inline-flex items-center gap-1.5 text-sm font-semibold text-slate-500">
            <BiCalendar className="text-base text-slate-400" />
            {entry.startDate} - {entry.endDate}
            <span className="ml-1 font-extrabold text-blue-700">
              ({calculateDuration(entry.startDate, entry.endDate)})
            </span>
          </span>
        </div>

        <p className="mb-4 text-[0.9375rem] leading-[1.75] text-slate-600">{entry.description}</p>

        <div className="mt-4">
          <div className="mb-2 inline-flex items-center gap-1.5 text-[0.75rem] font-extrabold uppercase tracking-[0.16em] text-slate-500">
            <BiCog className="text-slate-400" />
            Technologies
          </div>
          <div className="mt-1.5 flex flex-wrap gap-1.5">
            {entry.skills.map((skill) => (
              <span key={skill} className="tech-badge">
                {skill}
              </span>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}

export default function Employment() {
  const { jobs, training } = portfolioConfig.experience;
  const totalYears = calculateTotalYears(jobs);

  return (
    <div className="section-card fade-in">
      <p className="eyebrow">Experience</p>
      <h2 className="section-title mt-2">Employment History</h2>

      <div className="mb-7 inline-flex items-center gap-2 rounded-lg bg-slate-950 px-4 py-2.5 text-sm font-extrabold text-white shadow-lg">
        <BiBriefcaseFilled className="text-lg" />
        <span>{totalYears}+ years of experience</span>
      </div>

      <div className="relative pl-8" style={{ borderLeft: '2px solid #1f6feb', borderRadius: '2px' }}>
        {jobs.map((job, i) => (
          <TimelineEntry key={i} entry={job} />
        ))}
      </div>

      {training.length > 0 && (
        <>
          <hr className="my-9 border-slate-200" />
          <h2 className="mb-6 flex items-center gap-2.5 text-2xl font-extrabold tracking-normal text-slate-950">
            <BiAward className="text-cyan-600" />
            Part-Time Training Experience
          </h2>
          <div className="relative pl-8" style={{ borderLeft: '2px solid #0891b2', borderRadius: '2px' }}>
            {training.map((t, i) => (
              <TimelineEntry key={i} entry={t} isTraining />
            ))}
          </div>
        </>
      )}
    </div>
  );
}
